### ISSUE TITLE
Launch ToDo's

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/dot-precip-dash#18]
- [x] Make explainer text always visible
- [x] Add “scroll down to see” to header
- [x] Fix spacing everywhere (via "correct" bulma classes)
- [x] Are there any references to published research about this?  Check with Peter B & add if so.
- [x] Add link to [SNAP DOT Precip Project page](https://uaf-snap.org/project/future-projections-of-precipitation-for-alaska-infrastructure/). 
- [x] Fix font sizes
- [x] Add links to GH & example code
- [x] Add direct link to CKAN entry
- [x] Footer — fix text “a research group at…”
- [x] Footer — add link to privacy policy
